[terminal]
vt = next

[default_session]
# command = "agreety --cmd start-sway"
# command = "cage -s -- regreet"
command = "start-greeter"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "_greeter"
