#!/bin/sh
export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=niri
export LIBSEAT_BACKEND=seatd
export XCURSOR_THEME=Adwaita
export XCURSOR_SIZE=32
export GTK_THEME=Adwaita:dark
ulimit -n 1048576
exec niri --session
